project_id = "kdsjgzroyrcycckgkumb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[edge_runtime]
enabled = true
policy = "oneshot"

[functions.stripe-connect-status]
verify_jwt = true

[functions.stripe-connect-onboarding]
verify_jwt = true

[functions.charge-session]
verify_jwt = true

[functions.network-test]
verify_jwt = false
